"use client";

import Image from "next/image";
import Link from "next/link";
import { useMemo, useState } from "react";
import AnimateIn from "@/components/AnimateIn";
import ListingCard from "@/components/ListingCard";
import PropertyModal from "@/components/PropertyModal";
import ContactForm from "@/components/ContactForm";
import { listings } from "@/lib/listings";
import type { Listing } from "@/lib/types";
import { useApp } from "@/lib/context";
import { t } from "@/lib/i18n";

export default function Home() {
  const { lang, openCallPanel } = useApp();
  const tr = t(lang);
  const [selected, setSelected] = useState<Listing | null>(null);
  const [type, setType] = useState("all");
  const [municipality, setMunicipality] = useState("all");
  const [beds, setBeds] = useState("0");
  const [maxPrice, setMaxPrice] = useState(3500000);
  const [sort, setSort] = useState("featured");
  const municipalities = [...new Set(listings.map((item) => item.municipality))].sort();
  const filtered = useMemo(() => {
    const result = listings.filter((item) => (type === "all" || item.type === type) && (municipality === "all" || item.municipality === municipality) && item.bedrooms >= Number(beds) && item.price <= maxPrice);
    return [...result].sort((a,b) => sort === "low" ? a.price-b.price : sort === "high" ? b.price-a.price : Number(b.featured)-Number(a.featured));
  }, [type, municipality, beds, maxPrice, sort]);
  const copy = lang === "es" ? {
    eyebrow:"Bienes raíces · Puerto Rico", titleA:"Tu próxima dirección", titleB:"empieza con una conversación.", sub:"Propiedades extraordinarias, orientación cercana y un concierge bilingüe disponible incluso cuando el resto del mundo duerme.", explore:"Explorar propiedades", call:"Hablar ahora", statement:"La isla cambia. Tu forma de encontrar hogar también.", intro:"Una experiencia diseñada para mover decisiones, no solo mostrar listados.", all:"Todas", sale:"Venta", rent:"Alquiler", place:"Municipio", beds:"Habitaciones", max:"Precio máximo", order:"Orden", featured:"Destacadas", low:"Menor precio", high:"Mayor precio", clear:"Restablecer", found:"propiedades", process:"De interés a visita, en minutos.", processSub:"Cada propiedad conecta con un concierge que conserva el contexto y guía el próximo paso.", agent:"Maritza + tecnología que amplifica su atención.", agentBody:"La propuesta une el criterio humano de una profesional local con una experiencia digital que responde al instante. El resultado: menos oportunidades perdidas y más visitas coordinadas.", contact:"Cuéntanos qué estás buscando.", contactSub:"Este formulario funciona localmente en la demo y está listo para conectarse al CRM o calendario final.", neighborhoods:"La isla, a tu manera." } : {
    eyebrow:"Real estate · Puerto Rico", titleA:"Your next address", titleB:"starts with a conversation.", sub:"Extraordinary properties, local guidance, and a bilingual concierge available even while the rest of the world sleeps.", explore:"Explore properties", call:"Talk now", statement:"The island evolves. The way you find home should too.", intro:"An experience built to move decisions—not just display listings.", all:"All", sale:"Sale", rent:"Rent", place:"Municipality", beds:"Bedrooms", max:"Maximum price", order:"Sort", featured:"Featured", low:"Lowest price", high:"Highest price", clear:"Reset", found:"properties", process:"From interest to tour, in minutes.", processSub:"Every property connects to a concierge that keeps context and guides the next step.", agent:"Maritza + technology that extends her attention.", agentBody:"The concept combines a local professional's judgment with a digital experience that responds instantly. The outcome: fewer missed opportunities and more coordinated tours.", contact:"Tell us what you're looking for.", contactSub:"This form works locally in the demo and is ready to connect to the final CRM or calendar.", neighborhoods:"The island, your way." };

  return <>
    <section id="inicio" className="relative min-h-[94vh] overflow-hidden bg-charcoal text-white">
      <Image src="https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=2000&h=1300&fit=crop" alt={lang === "es" ? "Villa contemporánea frente al mar" : "Contemporary oceanfront villa"} fill priority sizes="100vw" className="object-cover opacity-70" />
      <div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(19,19,17,.92)_0%,rgba(19,19,17,.52)_55%,rgba(19,19,17,.12)_100%)]" />
      <div className="relative mx-auto flex min-h-[94vh] max-w-[1440px] items-end px-5 pb-16 pt-36 lg:px-10 lg:pb-24">
        <div className="max-w-4xl"><p className="mb-7 text-[10px] font-semibold uppercase tracking-[.3em] text-sand-light">{copy.eyebrow}</p><h1 className="font-serif text-[clamp(3.7rem,8.6vw,8.8rem)] font-normal leading-[.84] tracking-[-.055em]">{copy.titleA}<br/><em className="font-normal text-sea-light">{copy.titleB}</em></h1><p className="mt-8 max-w-xl text-base leading-7 text-white/65 sm:text-lg">{copy.sub}</p><div className="mt-9 flex flex-wrap gap-3"><Link href="#propiedades" className="rounded-full bg-white px-6 py-4 text-[10px] font-semibold uppercase tracking-[.15em] text-charcoal transition hover:bg-sea-light">{copy.explore}</Link><button onClick={() => openCallPanel("1")} className="rounded-full border border-white/35 bg-white/5 px-6 py-4 text-[10px] font-semibold uppercase tracking-[.15em] backdrop-blur transition hover:bg-white hover:text-charcoal">◉ {copy.call}</button></div></div>
      </div>
      <div className="absolute bottom-0 right-0 hidden w-80 border-l border-t border-white/15 bg-charcoal/55 p-6 backdrop-blur lg:block"><p className="text-[9px] uppercase tracking-[.22em] text-sand">24 / 7 · Bilingual</p><p className="mt-2 font-serif text-xl">{lang === "es" ? "Tu concierge no pierde una llamada." : "Your concierge never misses a call."}</p></div>
    </section>

    <section className="bg-ivory px-5 py-24 lg:px-10 lg:py-32"><div className="mx-auto grid max-w-[1440px] gap-10 lg:grid-cols-[.8fr_1.2fr]"><AnimateIn><p className="text-[10px] uppercase tracking-[.25em] text-sea-dark">MJV / 001</p></AnimateIn><AnimateIn delay={.1}><h2 className="max-w-4xl font-serif text-[clamp(2.8rem,5.5vw,5.8rem)] leading-[.95] tracking-[-.04em]">{copy.statement}</h2><p className="mt-7 max-w-xl leading-7 text-charcoal/55">{copy.intro}</p></AnimateIn></div></section>

    <section id="propiedades" className="scroll-mt-20 bg-[#efede8] px-5 py-20 lg:px-10 lg:py-28">
      <div className="mx-auto max-w-[1440px]"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[10px] uppercase tracking-[.25em] text-sea-dark">Portfolio conceptual</p><h2 className="mt-3 font-serif text-5xl sm:text-7xl">{tr.featured.title}</h2></div><p className="max-w-md text-sm leading-6 text-charcoal/50">{lang === "es" ? "Explora una colección ficticia que demuestra cómo se verían y funcionarían sus listados reales." : "Explore a fictional collection showing how real listings would look and work."}</p></div>
        <div className="mt-10 grid gap-3 rounded-2xl border border-charcoal/10 bg-white/65 p-4 backdrop-blur md:grid-cols-2 xl:grid-cols-6">
          <label className="text-[9px] uppercase tracking-wider text-charcoal/45">Tipo<select value={type} onChange={e=>setType(e.target.value)} className="mt-2 w-full bg-transparent text-sm text-charcoal outline-none"><option value="all">{copy.all}</option><option value="venta">{copy.sale}</option><option value="alquiler">{copy.rent}</option></select></label>
          <label className="text-[9px] uppercase tracking-wider text-charcoal/45">{copy.place}<select value={municipality} onChange={e=>setMunicipality(e.target.value)} className="mt-2 w-full bg-transparent text-sm text-charcoal outline-none"><option value="all">{copy.all}</option>{municipalities.map(x=><option key={x}>{x}</option>)}</select></label>
          <label className="text-[9px] uppercase tracking-wider text-charcoal/45">{copy.beds}<select value={beds} onChange={e=>setBeds(e.target.value)} className="mt-2 w-full bg-transparent text-sm text-charcoal outline-none"><option value="0">{copy.all}</option>{[1,2,3,4,5].map(x=><option key={x} value={x}>{x}+</option>)}</select></label>
          <label className="text-[9px] uppercase tracking-wider text-charcoal/45">{copy.max}<select value={maxPrice} onChange={e=>setMaxPrice(Number(e.target.value))} className="mt-2 w-full bg-transparent text-sm text-charcoal outline-none"><option value="500000">$500K</option><option value="1000000">$1M</option><option value="2000000">$2M</option><option value="3500000">$3.5M</option></select></label>
          <label className="text-[9px] uppercase tracking-wider text-charcoal/45">{copy.order}<select value={sort} onChange={e=>setSort(e.target.value)} className="mt-2 w-full bg-transparent text-sm text-charcoal outline-none"><option value="featured">{copy.featured}</option><option value="low">{copy.low}</option><option value="high">{copy.high}</option></select></label>
          <button onClick={()=>{setType("all");setMunicipality("all");setBeds("0");setMaxPrice(3500000);setSort("featured");}} className="rounded-xl border border-charcoal/15 px-3 py-3 text-[10px] font-semibold uppercase tracking-wider transition hover:bg-charcoal hover:text-white">{copy.clear}</button>
        </div>
        <p className="mt-5 text-xs uppercase tracking-[.15em] text-charcoal/45">{filtered.length} {copy.found}</p>
        {filtered.length ? <div className="mt-6 grid gap-6 md:grid-cols-2 xl:grid-cols-3">{filtered.map((listing,index)=><AnimateIn key={listing.id} delay={(index%3)*.06}><ListingCard listing={listing} onDetails={setSelected}/></AnimateIn>)}</div> : <div className="mt-8 rounded-2xl border border-charcoal/10 bg-white p-12 text-center"><p>{tr.filter.noResults}</p><button onClick={()=>{setType("all");setMunicipality("all");setBeds("0");setMaxPrice(3500000);}} className="mt-4 text-sm underline">{tr.filter.clearFilters}</button></div>}
      </div>
    </section>

    <section id="experiencia" className="scroll-mt-20 bg-charcoal px-5 py-24 text-white lg:px-10 lg:py-32"><div className="mx-auto max-w-[1440px]"><div className="grid gap-12 lg:grid-cols-2"><div><p className="text-[10px] uppercase tracking-[.25em] text-sea-light">Always-on experience</p><h2 className="mt-5 max-w-xl font-serif text-5xl leading-[.98] sm:text-7xl">{copy.process}</h2><p className="mt-6 max-w-lg leading-7 text-white/50">{copy.processSub}</p><button onClick={()=>openCallPanel("2")} className="mt-8 rounded-full bg-sea-light px-6 py-4 text-[10px] font-semibold uppercase tracking-[.15em] text-charcoal">{copy.call}</button></div><div className="space-y-3">{[["01",tr.concierge.step1,tr.concierge.step1Desc],["02",tr.concierge.step2,tr.concierge.step2Desc],["03",tr.concierge.step3,tr.concierge.step3Desc]].map(([n,title,body])=><AnimateIn key={n}><div className="grid grid-cols-[55px_1fr] gap-5 rounded-2xl border border-white/10 p-6 transition hover:border-sea-light/35 hover:bg-white/[.03]"><span className="font-serif text-2xl text-sea-light">{n}</span><div><h3 className="font-serif text-2xl">{title}</h3><p className="mt-2 text-sm leading-6 text-white/45">{body}</p></div></div></AnimateIn>)}</div></div></div></section>

    <section className="bg-ivory px-5 py-24 lg:px-10 lg:py-32"><div className="mx-auto max-w-[1440px]"><p className="text-[10px] uppercase tracking-[.25em] text-sea-dark">{copy.neighborhoods}</p><div className="mt-8 grid auto-rows-[300px] gap-4 md:grid-cols-3"><div className="relative overflow-hidden rounded-2xl md:col-span-2"><Image src="https://images.unsplash.com/photo-1518639192441-8fce0a366e2e?w=1400&h=800&fit=crop" alt="Puerto Rico coast" fill className="object-cover"/><span className="absolute bottom-5 left-5 font-serif text-3xl text-white">San Juan / Metro</span></div><div className="relative overflow-hidden rounded-2xl"><Image src="https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=900&h=900&fit=crop" alt="Caribbean beach" fill className="object-cover"/><span className="absolute bottom-5 left-5 font-serif text-3xl text-white">Oeste</span></div><div className="relative overflow-hidden rounded-2xl"><Image src="https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=900&h=900&fit=crop" alt="Mountain landscape" fill className="object-cover"/><span className="absolute bottom-5 left-5 font-serif text-3xl text-white">Cordillera</span></div><div className="relative overflow-hidden rounded-2xl md:col-span-2"><Image src="https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1400&h=800&fit=crop" alt="Luxury interior" fill className="object-cover"/><span className="absolute bottom-5 left-5 font-serif text-3xl text-white">Dorado / Norte</span></div></div></div></section>

    <section className="bg-sea-dark px-5 py-24 text-white lg:px-10"><div className="mx-auto grid max-w-[1440px] items-center gap-12 lg:grid-cols-[.8fr_1.2fr]"><div className="relative mx-auto grid aspect-square w-full max-w-md place-items-center overflow-hidden rounded-full border border-white/20 bg-[radial-gradient(circle_at_35%_30%,#a8c2bc,#527a78_55%,#263e3d)]"><span className="font-serif text-[clamp(4rem,10vw,8rem)] tracking-[-.08em] text-white/90">MJV</span><span className="absolute bottom-12 text-[9px] uppercase tracking-[.3em] text-white/55">Portrait placeholder</span></div><div><p className="text-[10px] uppercase tracking-[.25em] text-white/55">{tr.agent.title} · Puerto Rico</p><h2 className="mt-5 max-w-3xl font-serif text-5xl leading-[.98] sm:text-7xl">{copy.agent}</h2><p className="mt-7 max-w-xl leading-7 text-white/65">{copy.agentBody}</p><p className="mt-6 text-xs text-white/40">{lang === "es" ? "Retrato y credenciales finales se incorporan con aprobación de la clienta." : "Final portrait and credentials will be added with client approval."}</p></div></div></section>

    <section id="contacto" className="scroll-mt-20 bg-ivory px-5 py-24 lg:px-10 lg:py-32"><div className="mx-auto grid max-w-[1200px] gap-12 lg:grid-cols-2"><div><p className="text-[10px] uppercase tracking-[.25em] text-sea-dark">Next move</p><h2 className="mt-5 font-serif text-5xl leading-none sm:text-7xl">{copy.contact}</h2><p className="mt-6 max-w-md leading-7 text-charcoal/55">{copy.contactSub}</p></div><div className="rounded-[1.5rem] border border-charcoal/10 bg-white p-6 shadow-[0_24px_70px_rgba(20,20,18,.07)] sm:p-9"><ContactForm/></div></div></section>
    {selected && <PropertyModal key={selected.id} listing={selected} onClose={()=>setSelected(null)} />}
  </>;
}
