import { createRequire } from "node:module";
import path from "node:path";
import fs from "node:fs";
const require = createRequire(import.meta.url);
const puppeteer = require("C:/Users/Aleck's Corp/node_modules/puppeteer");
const out = path.resolve("artifacts");
const target = process.env.TARGET_URL || "http://localhost:3000";
fs.mkdirSync(out, { recursive: true });
const browser = await puppeteer.launch({ headless: true, executablePath: "C:/Program Files/Google/Chrome/Application/chrome.exe", args: ["--no-sandbox"] });
const page = await browser.newPage();
const errors = [];
page.on("console", msg => { if (msg.type() === "error") errors.push(`console: ${msg.text()}`); });
page.on("pageerror", err => errors.push(`pageerror: ${err.message}`));
const clickText = async (text) => {
  const clicked = await page.evaluate((label) => {
    const el = [...document.querySelectorAll("button,a")].find(node => node.textContent?.trim().includes(label));
    if (!el) return false;
    el.click(); return true;
  }, text);
  if (!clicked) throw new Error(`Control not found: ${text}`);
};
const textExists = async text => page.evaluate(label => document.body.innerText.includes(label), text);

await page.setViewport({ width: 1440, height: 1000, deviceScaleFactor: 1 });
await page.goto(target, { waitUntil: "networkidle2" });
if (!(await textExists("Tu próxima dirección"))) throw new Error("Spanish hero missing");
for (let y = 0; y < await page.evaluate(() => document.body.scrollHeight); y += 750) {
  await page.evaluate(scrollY => window.scrollTo(0, scrollY), y);
  await new Promise(r => setTimeout(r, 120));
}
await page.evaluate(() => window.scrollTo(0, 0));
await page.screenshot({ path: path.join(out,"desktop-home.png"), fullPage: true });
await page.evaluate(() => document.querySelector("#propiedades")?.scrollIntoView());
await page.click("article.property-card button");
await page.waitForSelector('[role="dialog"]');
if (!(await textExists("Amenidades"))) throw new Error("Property details missing amenities");
await page.screenshot({ path: path.join(out,"property-modal.png") });
await page.keyboard.press("Escape");
await page.waitForFunction(() => !document.querySelector('[aria-labelledby="property-title"]'));
await clickText("Llámame ahora");
await page.waitForSelector('[aria-labelledby="call-title"]');
await clickText("Iniciar Llamada");
await new Promise(r => setTimeout(r, 1800));
if (!(await textExists("Prueba una pregunta"))) throw new Error("Call demo did not connect");
await clickText("Visita");
await page.waitForSelector("#tour-name");
await page.type("#tour-name", "Cliente Demo");
await page.$eval('#tour-name', el => { const input = el.closest('form').querySelector('input[type="date"]'); const setter = Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, "value").set; setter.call(input, "2026-10-15"); input.dispatchEvent(new Event("input", { bubbles: true })); });
await page.$eval('#tour-name', el => { const input = el.closest('form').querySelector('input[type="time"]'); const setter = Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, "value").set; setter.call(input, "14:00"); input.dispatchEvent(new Event("input", { bubbles: true })); });
await page.$eval('#tour-name', el => el.closest('form').requestSubmit());
await new Promise(r => setTimeout(r, 200));
if (!(await textExists("Solicitud de visita registrada localmente"))) throw new Error("Tour local success missing");
await page.screenshot({ path: path.join(out,"call-concierge.png") });
await page.keyboard.press("Escape");
await page.waitForFunction(() => !document.querySelector('[aria-labelledby="call-title"]'));
const selects = await page.$$("#propiedades select");
await selects[0].select("alquiler");
await new Promise(r => setTimeout(r, 250));
const cardsAfterFilter = await page.$$eval("article.property-card", els => els.length);
if (cardsAfterFilter < 1 || cardsAfterFilter >= 8) throw new Error(`Unexpected rental filter count: ${cardsAfterFilter}`);
await clickText("English");
if (!(await textExists("Your next address"))) throw new Error("Language switch failed");
await page.evaluate(() => document.querySelector("#contacto")?.scrollIntoView());
await page.click('#contacto button[type="submit"]');
if (!(await textExists("This field is required"))) throw new Error("Contact validation missing");
await page.type("#contact-name", "Demo Buyer");
await page.type("#contact-email", "buyer@example.com");
await page.type("#contact-phone", "7875550100");
await page.type("#contact-message", "Looking for an oceanfront property.");
await page.click('#contacto button[type="submit"]');
if (!(await textExists("Demo complete"))) throw new Error("Contact local success missing");
await page.setViewport({ width: 390, height: 844, deviceScaleFactor: 1 });
await page.goto(target, { waitUntil: "networkidle2" });
const overflow = await page.evaluate(() => document.documentElement.scrollWidth - window.innerWidth);
if (overflow > 1) throw new Error(`Mobile horizontal overflow: ${overflow}px`);
await page.screenshot({ path: path.join(out,"mobile-home.png"), fullPage: true });
const result = { title: await page.title(), cardsAfterFilter, mobileOverflowPx: overflow, consoleErrors: errors, screenshots: fs.readdirSync(out).sort() };
console.log(JSON.stringify(result, null, 2));
await browser.close();
if (errors.length) process.exitCode = 2;
